import './style.css';
import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { SpinePlayer } from '../pet/spine-player';
import { createModel,createShell,batchModel } from './models';
import { CATALOG,BY_ID,DEFAULT_LAYOUT,SAVE_KEY,restore,legal,extent,seatWorld } from './layout.mjs';

const $=id=>document.getElementById(id),status=text=>$('status').textContent=text;
const urls=import.meta.glob('./models/*.glb',{eager:true,query:'?url',import:'default'});
const scene=new T.Scene(),world=new T.Group();scene.add(world);
const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power',preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('stage').append(renderer.domElement);
const camera=new T.PerspectiveCamera(36,1,.1,100),controls=new OrbitControls(camera,renderer.domElement);
controls.target.set(0,1,0);controls.enableDamping=true;controls.dampingFactor=.1;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=23;controls.minPolarAngle=.75;controls.maxPolarAngle=1.48;controls.minAzimuthAngle=-.52;controls.maxAzimuthAngle=.52;
const hemi=new T.HemisphereLight('#c4dce2','#56482d',2);scene.add(hemi);
const sun=new T.DirectionalLight('#ffe0aa',3.1);sun.position.set(-3,7,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-7;sun.shadow.camera.right=7;sun.shadow.camera.top=6;sun.shadow.camera.bottom=-6;sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;sun.shadow.radius=3;scene.add(sun);
const cool=new T.DirectionalLight('#90c3e3',1.2);cool.position.set(1,3,-5);scene.add(cool);
const shell=batchModel(createShell(()=>{needsRender=true;}));world.add(shell);
const floorLight=new T.PointLight('#ffb95c',4,5,2);floorLight.position.set(2.25,.8,.6);world.add(floorLight);
const furniture=new Map(),templates=new Map(),ray=new T.Raycaster(),pointer=new T.Vector2(),floor=new T.Plane(new T.Vector3(0,1,0),0);
const marker=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({color:'#c0cf8e',transparent:true,opacity:.22,depthWrite:false,side:T.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=.05;marker.visible=false;world.add(marker);
const grid=new T.GridHelper(9,45,'#99b5a0','#99b5a0');grid.material.transparent=true;grid.material.opacity=.15;grid.position.y=.035;grid.visible=false;world.add(grid);
let layout=structuredClone(DEFAULT_LAYOUT),selected=null,drag=null,dirty=false,view='home',tower=null,disposed=false,draws=0,last=0,frame=0,needsRender=true,transition=null;
const history=[],actors=[];let actorCursor=0;
try{const raw=localStorage.getItem(SAVE_KEY);if(raw)layout=restore(JSON.parse(raw));}catch{status('存档暂时不可读，先展示默认茶室');}
function changed(){dirty=true;needsRender=true;$('save').textContent='保存布置 ·';}
function snapshot(){history.push(JSON.stringify(layout));if(history.length>40)history.shift();$('undo').disabled=false;}
function instance(asset){const o=(templates.get(asset)||createModel(asset)).clone(true);o.traverse(n=>{if(n.isMesh){n.castShadow=asset!=='jade-rug';n.receiveShadow=true;}});return o;}
function rebuild(){for(const g of furniture.values())world.remove(g);furniture.clear();for(const p of layout){const g=instance(p.asset);g.position.set(p.x,0,p.z);g.rotation.y=p.angle;g.userData.key=p.key;world.add(g);furniture.set(p.key,g);}if(selected&&!furniture.has(selected))selected=null;refreshSelection();updateActors(0);needsRender=true;}
function chosen(){return layout.find(p=>p.key===selected);}
function refreshSelection(){const p=chosen();$('selection').hidden=!p||view==='tower';marker.visible=!!p&&view!=='tower';if(!p)return;const meta=BY_ID[p.asset];$('selected-name').textContent=meta.name;$('selected-info').textContent=meta.category==='seat'?'双人座位 · 可替换坐具':meta.category==='rug'?'地毯可以放在家具下方':'独立家具 · 自由摆放';
 const select=$('replace');select.replaceChildren();for(const a of CATALOG.filter(a=>a.category===meta.category)){const opt=document.createElement('option');opt.value=a.id;opt.textContent=a.name;select.append(opt);}select.value=p.asset;select.disabled=select.options.length<2;
 $('sit').hidden=!meta.seats;$('sit').disabled=!actors.length;const e=extent(p);marker.scale.set(e.x*2+.1,e.z*2+.1,1);marker.position.set(p.x,.046,p.z);marker.material.color.set('#c0cf8e');
}
function select(key){selected=key;refreshSelection();needsRender=true;}
function cancelDrag(){if(!drag)return;const g=furniture.get(drag.key);if(g){g.position.set(drag.original.x,0,drag.original.z);g.rotation.y=drag.original.angle;}drag=null;controls.enabled=true;refreshSelection();needsRender=true;}
function point(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.ray.intersectPlane(floor,new T.Vector3());}
function hit(){for(const h of ray.intersectObjects([...furniture.values()],true)){let n=h.object;while(n&&!n.userData.key)n=n.parent;if(n)return n.userData.key;}return null;}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0||view==='tower')return;const at=point(e),key=hit();if(!key||!at){select(null);return;}select(key);const p=chosen();controls.enabled=false;transition=null;drag={key,original:{...p},candidate:{...p},start:[e.clientX,e.clientY],offset:{x:p.x-at.x,z:p.z-at.z},moved:false,valid:true};renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const at=point(e);if(!at)return;if(Math.hypot(e.clientX-drag.start[0],e.clientY-drag.start[1])<4&&!drag.moved)return;drag.moved=true;const snap=$('snap').checked ? .2 : .01;const p={...drag.original,x:Math.round((at.x+drag.offset.x)/snap)*snap,z:Math.round((at.z+drag.offset.z)/snap)*snap};drag.candidate=p;drag.valid=legal(p,layout);const g=furniture.get(drag.key);g.position.set(p.x,.1,p.z);marker.position.set(p.x,.048,p.z);marker.material.color.set(drag.valid?'#b9d58b':'#ed8f74');status(drag.valid?'松手放下家具':'这里放不下，松手会回到原位');needsRender=true;});
renderer.domElement.addEventListener('pointerup',()=>{if(!drag)return;const d=drag;cancelDrag();if(d.moved&&d.valid){snapshot();Object.assign(layout.find(p=>p.key===d.key),d.candidate);rebuild();changed();status('已放下，可以继续调整');}else if(d.moved)status('保留原来的位置');});
renderer.domElement.addEventListener('pointercancel',cancelDrag);renderer.domElement.addEventListener('lostpointercapture',cancelDrag);window.addEventListener('blur',cancelDrag);
function move(dx,dz,angle=0){const p=chosen();if(!p)return;const next={...p,x:p.x+dx,z:p.z+dz,angle:(p.angle+angle)%(Math.PI*2)};if(!legal(next,layout)){status('空间不足，请先把家具移到空处');return;}snapshot();Object.assign(p,next);rebuild();changed();}
$('rotate').onclick=()=>move(0,0,Math.PI/4);$('remove').onclick=()=>{if(!selected)return;snapshot();for(const a of actors)if(a.seatKey===selected)stand(a);layout=layout.filter(p=>p.key!==selected);selected=null;rebuild();changed();status('家具已收起，可从下方重新添加');};
$('replace').onchange=e=>{const p=chosen();if(!p)return;const next={...p,asset:e.target.value};if(!legal(next,layout)){e.target.value=p.asset;status('这件家具需要更大的空间');return;}snapshot();Object.assign(p,next);rebuild();changed();status('家具已替换，位置和座位已保留');};
function add(asset){const meta=BY_ID[asset];if(layout.length>=30){status('样板最多摆放 30 件家具');return;}for(let z=-1.8;z<=2;z+=.35)for(let x=-3.8;x<=4;x+=.35){const p={key:crypto.randomUUID(),asset,x,z,angle:0};if(legal(p,layout)){snapshot();layout.push(p);rebuild();select(p.key);changed();status('已添入'+meta.name+'，拖到喜欢的位置');return;}}status('暂时没有足够空位，可以先收起一件家具');}
$('undo').onclick=()=>{if(!history.length)return;cancelDrag();layout=JSON.parse(history.pop());$('undo').disabled=!history.length;rebuild();changed();status('已撤销上一步');};
$('save').onclick=()=>{cancelDrag();try{localStorage.setItem(SAVE_KEY,JSON.stringify(layout));dirty=false;$('save').textContent='保存布置';status('已保存这间试住茶室');}catch{status('保存失败，布置仍在，请重试');}};
$('reset').onclick=()=>{cancelDrag();snapshot();layout=structuredClone(DEFAULT_LAYOUT);for(const a of actors)stand(a);rebuild();changed();status('已恢复茶室，可撤销或保存');};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('art-dialog').open)return;if(e.key==='Escape'){cancelDrag();select(null);return;}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(!chosen()||view==='tower')return;const n=e.shiftKey ? .2 : .05;if(e.key==='ArrowLeft')move(-n,0);else if(e.key==='ArrowRight')move(n,0);else if(e.key==='ArrowUp')move(0,-n);else if(e.key==='ArrowDown')move(0,n);else if(e.key.toLowerCase()==='r')move(0,0,Math.PI/4);else return;e.preventDefault();});

function setView(next){cancelDrag();view=next;for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===next));grid.visible=next==='edit';
 if(next==='tower'&&!tower){tower=new T.Group();const sh=shell.clone(true);tower.add(sh);for(const p of DEFAULT_LAYOUT){const g=instance(p.asset);g.position.set(p.x,0,p.z);g.rotation.y=p.angle;tower.add(g);}tower.position.y=3.55;tower.traverse(n=>{if(n.isLight)n.visible=false;});scene.add(tower);}if(tower)tower.visible=next==='tower';
 const pos=next==='edit'?[6,9,13]:next==='tower'?[5,7.8,21]:[2.6,4.6,12.8],target=next==='tower'?[0,2.8,0]:[0,1,0];controls.maxDistance=next==='tower'?29:23;transition={from:camera.position.clone(),to:new T.Vector3(...pos),start:performance.now(),targetFrom:controls.target.clone(),targetTo:new T.Vector3(...target)};refreshSelection();$('room-caption').textContent=next==='tower'?'两层展示 · 上层为陈设样例':'青竹 · 原木 · 青瓷';status(next==='tower'?'楼层总览 · 上层为展示样例，布置请切回生活或布置视角':'拖动家具布置，拖动空处调整视角');needsRender=true;
}
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);
function orbit(delta){transition=null;const offset=camera.position.clone().sub(controls.target),s=new T.Spherical().setFromVector3(offset);s.theta=T.MathUtils.clamp(s.theta+delta,-.5,.5);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();needsRender=true;}
$('left').onclick=()=>orbit(-.13);$('right').onclick=()=>orbit(.13);
function zoom(f){transition=null;const v=camera.position.clone().sub(controls.target);v.setLength(T.MathUtils.clamp(v.length()*f,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(v);controls.update();needsRender=true;}
$('zoom-in').onclick=()=>zoom(.9);$('zoom-out').onclick=()=>zoom(1.1);controls.addEventListener('change',()=>{needsRender=true;});controls.addEventListener('start',()=>{transition=null;});
$('art').src=new URL('./art/tea-concept.png',import.meta.url).href;$('concept').onclick=()=>$('art-dialog').showModal();$('close-art').onclick=()=>$('art-dialog').close();

function stand(a){a.seatKey=null;a.state='standing';a.anchor=null;a.anchorAt=performance.now()+100;a.player.play('idle',true);a.mesh.position.set(-.75+actors.indexOf(a)*1.5,.78,1.9);needsRender=true;}
$('stand').onclick=()=>{for(const a of actors)stand(a);status('已回到地面');};
$('sit').onclick=()=>{const p=chosen();if(!p||!BY_ID[p.asset].seats)return;const occupied=new Set(actors.filter(a=>a.seatKey===p.key).map(a=>a.seatIndex));const index=[0,1].find(i=>!occupied.has(i));if(index===undefined){status('这张软榻已经坐满了');return;}const a=actors.find(a=>!a.seatKey)||actors[(actorCursor++)%actors.length];if(!a)return;a.seatKey=p.key;a.seatIndex=index;a.state='seated';a.anchor=null;a.anchorAt=performance.now()+100;a.player.play('perch',true);updateActors(0);status('已试坐 · 座位随家具移动，第二次点击可坐入另一位');};
async function loadActors(){if(!window.qbot?.characters){status('茶室已就绪；从客户端打开可预览已有 Spine 角色');return;}try{const all=await window.qbot.characters.list();const chars=all.filter(c=>c.manifest?.spine?.actions?.perch).slice(0,2);for(const char of chars){const manifest=structuredClone(char.manifest);delete manifest.spine.seat;const host=document.createElement('div');$('sources').append(host);const player=new SpinePlayer(host,char.dirId,manifest,()=>{});const canvas=host.querySelector('canvas');const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;tex.minFilter=T.LinearFilter;const mat=new T.MeshBasicMaterial({map:tex,transparent:true,alphaTest:.15,depthWrite:true,side:T.DoubleSide});const mesh=new T.Mesh(new T.PlaneGeometry(2,2),mat);mesh.name='Spine-guest';world.add(mesh);const a={player,host,canvas,tex,mesh,seatKey:null,seatIndex:0,state:'standing'};actors.push(a);stand(a);}refreshSelection();if(!chars.length)status('家具已就绪；已有角色中暂无可用的 Spine 坐姿');}catch{status('家具已就绪，角色暂时未能加载');}}
function updateActors(){for(const a of actors){if(a.canvas.dataset.ready!=='true'){a.mesh.visible=false;continue;}a.mesh.visible=true;a.tex.needsUpdate=true;if(!a.anchor&&performance.now()>a.anchorAt)a.anchor=a.player.getSceneAnchor(a.seatKey?'seat':'floor');const p=layout.find(p=>p.key===a.seatKey);if(a.seatKey&&!p){stand(a);continue;}if(p){const display=drag?.key===p.key?drag.candidate:p;const s=seatWorld(display,a.seatIndex);if(s){const g=furniture.get(p.key);const forward=.45,ax=((a.anchor?.x??.5)-.5)*2,ay=((a.anchor?.y??.73)-.5)*2;a.mesh.position.set(s.x+Math.sin(p.angle)*forward-Math.cos(p.angle)*ax,s.y+ay+(g?.position.y||0),s.z+Math.cos(p.angle)*forward+Math.sin(p.angle)*ax);a.mesh.rotation.set(0,p.angle,0);}}else{if(a.anchor)a.mesh.position.y=(a.anchor.y-.5)*2;a.mesh.rotation.set(0,Math.atan2(camera.position.x-a.mesh.position.x,camera.position.z-a.mesh.position.z)*.35,0);}}}
function resize(){const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=2*Math.atan(Math.tan(Math.PI/10)*Math.max(1,1.9/camera.aspect))*180/Math.PI;camera.updateProjectionMatrix();needsRender=true;}
const observer=new ResizeObserver(resize);observer.observe($('stage'));
function tick(now){if(disposed)return;frame=requestAnimationFrame(tick);if(document.hidden||now-last<1000/30)return;last=now;controls.update();if(transition){const t=Math.min(1,(now-transition.start)/650),v=1-(1-t)**3;camera.position.lerpVectors(transition.from,transition.to,v);controls.target.lerpVectors(transition.targetFrom,transition.targetTo,v);controls.update();if(t===1)transition=null;needsRender=true;}if(actors.length){updateActors();needsRender=true;}if(needsRender){const lamp=layout.find(p=>p.asset==='lantern');floorLight.visible=!!lamp;if(lamp)floorLight.position.set(lamp.x,.8,lamp.z);renderer.render(scene,camera);draws++;document.body.dataset.draws=String(draws);needsRender=false;}}
document.addEventListener('visibilitychange',()=>{for(const a of actors)a.player.setSuspended(document.hidden);needsRender=true;last=0;});
async function thumbnails(){const tr=new T.WebGLRenderer({alpha:true,antialias:true});tr.setSize(184,130);tr.outputColorSpace=T.SRGBColorSpace;tr.toneMapping=T.ACESFilmicToneMapping;const sc=new T.Scene();sc.add(new T.HemisphereLight('#ffffff','#7a6951',3));const l=new T.DirectionalLight('#ffe6bd',3);l.position.set(-3,5,4);sc.add(l);const cam=new T.PerspectiveCamera(35,184/130,.01,30);
 for(const meta of CATALOG){const obj=instance(meta.id);sc.add(obj);const bound=new T.Box3().setFromObject(obj),size=bound.getSize(new T.Vector3()),center=bound.getCenter(new T.Vector3());const dist=Math.max(size.x*.9,size.y,size.z)*2;cam.position.copy(center).add(new T.Vector3(dist*.65,dist*.5,dist));cam.lookAt(center);tr.render(sc,cam);const b=document.createElement('button');b.className='item';b.dataset.asset=meta.id;b.setAttribute('aria-label','添加'+meta.name);const img=new Image();img.src=tr.domElement.toDataURL();img.alt='';const name=document.createElement('span');name.textContent=meta.name;const plus=document.createElement('em');plus.textContent='+';b.append(img,name,plus);b.onclick=()=>{if(view==='tower')setView('home');add(meta.id);};$('shelf').append(b);sc.remove(obj);}tr.dispose();tr.forceContextLoss();}
async function boot(){for(const meta of CATALOG){const url=urls[`./models/${meta.id}.glb`];let object;try{object=url?(await new GLTFLoader().loadAsync(url)).scene:createModel(meta.id);}catch{object=createModel(meta.id);document.body.dataset.modelFallback='true';}templates.set(meta.id,batchModel(object));}rebuild();camera.position.set(2.6,4.6,12.8);controls.update();resize();await thumbnails();document.body.dataset.ready='true';status('茶室已就绪 · 选择家具，试着挪一挪');frame=requestAnimationFrame(tick);await loadActors();}
// Inspection/export hooks are local to this specimen and never mutate account state.
window.tea3d={get layout(){return structuredClone(layout);},get actors(){return actors.map(a=>({state:a.state,seatKey:a.seatKey,ready:a.canvas.dataset.ready,error:a.canvas.dataset.error,position:a.mesh.position.toArray()}));},get draws(){return draws;},select,setView,add,project(key){const p=furniture.get(key);if(!p)return null;const v=new T.Box3().setFromObject(p).getCenter(new T.Vector3()).project(camera),r=renderer.domElement.getBoundingClientRect();return{x:Math.round(r.left+(v.x+1)*r.width/2),y:Math.round(r.top+(1-v.y)*r.height/2)};},projectFloor(x,z){const v=new T.Vector3(x,0,z).project(camera),r=renderer.domElement.getBoundingClientRect();return{x:Math.round(r.left+(v.x+1)*r.width/2),y:Math.round(r.top+(1-v.y)*r.height/2)};},async exportModels(){const result={};for(const meta of CATALOG){const buffer=await new GLTFExporter().parseAsync(createModel(meta.id),{binary:true});result[meta.id]=Array.from(new Uint8Array(buffer));}return result;},stats(){return{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,models:templates.size,dirty};}};
window.addEventListener('beforeunload',()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();for(const a of actors){a.player.dispose();a.tex.dispose();}const geos=new Set(),mats=new Set(),textures=new Set();for(const root of [scene,...templates.values()])root.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){mats.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v);}});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();});
void boot().catch(e=>{status('茶室未能加载：'+e.message);document.body.dataset.error=e.message;console.error(e);});
