/** Run after `npm run build -w app`. Requires Playwright (or PLAYWRIGHT_MODULE absolute path). */
const { _electron: electron } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const { mkdtemp, mkdir, rm } = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const root = path.resolve(__dirname, '..');
(async () => {
  const data = await mkdtemp(path.join(os.tmpdir(),'qbot-nursery-qa-'));
  const output = path.join(root,'.superpowers/nursery-preview');
  await mkdir(output,{recursive:true});
  const app = await electron.launch({ executablePath:require('electron'),args:[path.join(root,'app/test/fixtures/nursery-main.cjs')],env:{...process.env,QBOT_QA_DATA:data} });
  try {
    const page=await app.firstWindow();const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    const shot=async name=>{await page.screenshot({path:path.join(output,`${name}.png`)});};
    const push=async status=>app.evaluate((_electron,st)=>global.qa.push(st),status);
    const label=async text=>page.getByRole('heading',{name:text,exact:true}).waitFor();
    const stage=(patch={})=>({stage:'actions',running:true,cloud:true,actions:{idle:{status:'done'},drag:{status:'generating_video'}},...patch});
    await page.waitForSelector('#scene canvas');
    await shot('home');
    await page.getByRole('button',{name:/走近孵化台/}).focus();await page.keyboard.press('Enter');
    await label('从一张图片开始。');
    await page.getByText('孵化资格已连接 · 不限次数迎接新朋友',{exact:true}).waitFor();
    await page.getByRole('button',{name:/开始孵化/}).click();
    await page.getByText('先把一张角色图片放上孵化台。',{exact:true}).waitFor();
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='start').length),0);
    await page.locator('input[type=file]').setInputFiles(path.join(root,'app/resources/presets/mascot/source.png'));
    await page.getByLabel('它的名字',{exact:true}).fill('栗子');
    await page.getByRole('button',{name:'回小屋',exact:true}).click();
    await page.getByRole('button',{name:/走近孵化台/}).click();
    assert.equal(await page.getByLabel('它的名字',{exact:true}).inputValue(),'栗子');
    await page.locator('#paper').evaluate(n=>n.scrollTop=0);await shot('draft');
    await page.getByRole('button',{name:/开始孵化/}).click();
    await label('正在描绘你的朋友');
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='start').length),1);
    await app.evaluate(()=>global.qa.win.webContents.send('hatch:cloudStatus',{dirId:'other',status:{stage:'done',actions:{}}}));
    await label('正在描绘你的朋友');
    await push(stage({stage:'awaiting_pick',candidateUrls:['qbot-asset://new-friend/turnaround.png']}));
    await label('是你想见到的样子吗？');await shot('appearance');
    await page.getByRole('button',{name:'就是它，开始学习动作',exact:true}).click();
    await label('它正在学着陪伴你');await shot('learning');
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='pick').length),1);
    await page.getByRole('button',{name:'去小屋里等它',exact:true}).click();
    const done=await app.evaluate(()=>({stage:'done',cloud:true,running:false,actions:global.qa.manifest.actions}));
    await push(done);assert.equal(await page.locator('#paper').isVisible(),false);
    await page.getByRole('button',{name:/走近孵化台/}).click();
    await page.getByRole('button',{name:'带它回到桌面',exact:true}).waitFor();
    await page.waitForFunction(()=>[...document.querySelectorAll('#actor video')].some(v=>v.currentTime>0&&v.style.visibility==='visible'));
    await shot('birth');
    // Actual decoder disposal on hidden and recovery on return, in the native Electron window.
    await app.evaluate(()=>global.qa.win.minimize());await page.waitForFunction(()=>document.querySelectorAll('#actor video').length===0,{},{polling:100});
    assert.equal(await page.locator('#actor video').count(),0);
    await app.evaluate(()=>{global.qa.win.restore();global.qa.win.show();global.qa.win.focus();});
    await page.waitForFunction(()=>[...document.querySelectorAll('#actor video')].some(v=>v.currentTime>0&&v.style.visibility==='visible'));
    await app.evaluate(()=>{global.qa.failActivate=true;});
    await page.getByRole('button',{name:'带它回到桌面',exact:true}).click();
    await page.getByRole('status').filter({hasText:'领取暂时失败'}).waitFor();
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='desktop').length),0);
    await push(stage({stage:'failed',running:false,error:'网络暂时断开，进度已经保留。',actions:{idle:{status:'done'},drag:{status:'failed',error:'模型暂时不可用'}}}));
    await label('孵化需要你帮忙');await shot('interrupted');
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='resume').length),0);
    await page.getByRole('button',{name:'继续学习未完成动作',exact:true}).click();
    await page.getByRole('button',{name:'确认继续',exact:true}).click();
    await label('它正在学着陪伴你');
    assert.equal(await app.evaluate(()=>global.qa.calls.filter(c=>c[0]==='resume').length),1);
    await page.getByRole('button',{name:'回小屋',exact:true}).click();
    await page.getByRole('button',{name:/翻开手记/}).click();
    await page.getByRole('button',{name:/小青/}).waitFor();await shot('ledger');
    await page.getByRole('button',{name:/小青/}).click();
    await page.waitForFunction(()=>[...document.querySelectorAll('#actor video')].some(v=>v.currentTime>0));
    await page.emulateMedia({reducedMotion:'reduce'});
    await app.evaluate(()=>global.qa.win.setSize(840,570));
    await shot('small-window');
    assert.equal(await page.locator('#paper').evaluate(n=>{const b=n.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth&&b.bottom<=innerHeight;}),true);
    await page.keyboard.press('Escape');assert.equal(await page.locator('#paper').isVisible(),false);
    await app.evaluate(()=>{global.qa.win.setSize(1120,760);global.qa.failActivate=false;});
    await push(done);
    await page.getByRole('button',{name:/走近孵化台/}).click();
    await page.getByRole('button',{name:'带它回到桌面',exact:true}).waitFor();
    await page.waitForFunction(()=>[...document.querySelectorAll('#actor video')].some(v=>v.currentTime>0));
    await shot('birth');
    const closed=page.waitForEvent('close');await page.getByRole('button',{name:'带它回到桌面',exact:true}).click();await closed;
    assert.deepEqual(errors,[]);
    console.log('PASS: image validation, Chinese name/draft retention, generation, appearance approval, honest progress, background completion, real WebM playback, minimize/restore decoder lifecycle, failed adoption, explicit retry, ledger, reduced motion, 840×570 layout, desktop handoff.');
    console.log(`Screenshots: ${output}`);
  } finally { await app.close().catch(()=>{});await rm(data,{recursive:true,force:true}); }
})().catch(e=>{console.error(e);process.exitCode=1;});
