import {describe,it,expect} from 'vitest';
import {initialGarden,transition,validateGarden} from '../src/main/garden/rules';
import {ensureLife} from '../src/main/garden/life-rules';
import {enableV3} from '../src/main/garden/v3-rules';
import {CAPSULE_POOL} from '../src/shared/social-economy';
import {equippedAppearance} from '../src/shared/appearances';
const now=1790630400000;let sequence=0;const rng={id:()=>`appearance-${++sequence}`,random:()=>.1};
function state(){const s=initialGarden(now,rng);ensureLife(s,now,rng,'one');ensureLife(s,now,rng,'two');enableV3(s,now);s.coins=20000;s.economy!.tokens=600;return s;}
const act=(s:ReturnType<typeof state>,command:Parameters<typeof transition>[1])=>transition(s,command,now,rng).state;
function draw(s:ReturnType<typeof state>,tier:number,item:number){let i=0;return transition(s,{type:'capsuleDraw',count:1},now,{id:rng.id,random:()=>[tier,item][i++]??0}).state;}
describe('permanent appearances and exclusive equipment',()=>{
  it('migrates an older save without granting items or changing currency',()=>{const s=state();delete s.economy!.appearances;const before=s.coins;validateGarden(s);enableV3(s,now);expect(s.economy!.appearances).toEqual({owned:{},equipped:{}});expect(s.coins).toBe(before);expect(enableV3(s,now)).toBe(false);});
  it('purchases exactly once and rejects insufficient money and unknown items atomically',()=>{const s=state(),b=act(s,{type:'buyAppearance',item:'petal-steps'});expect(b.coins).toBe(16000);expect(s.coins).toBe(20000);expect(b.economy!.appearances!.owned['petal-steps']).toBe(true);expect(()=>act(b,{type:'buyAppearance',item:'petal-steps'})).toThrow('已经拥有');expect(()=>act({...s,coins:10},{type:'buyAppearance',item:'eclipse-portal'})).toThrow('不足');expect(()=>act(s,{type:'buyAppearance',item:'blue-flame'})).toThrow('不存在');});
  it('rejects unowned equipment and unknown characters',()=>{const s=state();expect(()=>act(s,{type:'equipAppearance',item:'petal-steps',actor:'one'})).toThrow('先获得');const b=act(s,{type:'buyAppearance',item:'petal-steps'});expect(()=>act(b,{type:'equipAppearance',item:'petal-steps',actor:'stranger'})).toThrow('自己已有');expect(()=>act(b,{type:'equipAppearance',item:'petal-steps',actor:'__proto__'})).toThrow();});
  it('moves an item to one character atomically, persists, and unequips',()=>{let s=act(state(),{type:'buyAppearance',item:'petal-steps'});s=act(s,{type:'equipAppearance',item:'petal-steps',actor:'one'});s=act(s,{type:'equipAppearance',item:'petal-steps',actor:'two'});s=validateGarden(JSON.parse(JSON.stringify(s)));expect(equippedAppearance(s.economy!.appearances,'one','petal-steps')).toBe(false);expect(equippedAppearance(s.economy!.appearances,'two','petal-steps')).toBe(true);s=act(s,{type:'equipAppearance',item:'petal-steps',actor:null});expect(s.economy!.appearances!.equipped).toEqual({});expect(s.economy!.appearances!.owned['petal-steps']).toBe(true);});
  it('allows entry and footsteps on the same character without cloning either unlock',()=>{let s=state();for(const item of ['petal-steps','eclipse-portal']){s=act(s,{type:'buyAppearance',item});s=act(s,{type:'equipAppearance',item,actor:'one'});}expect(Object.values(s.economy!.appearances!.equipped)).toEqual(['one','one']);});
  it('delivers both cosmetics from the real pool, refunds duplicates, preserves equipment',()=>{let s=draw(state(),.8,.65);expect(s.economy!.appearances!.owned['petal-steps']).toBe(true);s=act(s,{type:'equipAppearance',item:'petal-steps',actor:'one'});const tokens=s.economy!.tokens;s=draw(s,.8,.65);expect(s.economy!.tokens).toBe(tokens-60+30);expect(s.economy!.lastCapsule!.rewards[0].duplicateTokens).toBe(30);expect(s.economy!.appearances!.equipped['petal-steps']).toBe('one');s=draw(s,.99,.9);expect(s.economy!.appearances!.owned['eclipse-portal']).toBe(true);expect(s.economy!.epicMisses).toBe(0);});
  it('keeps each rarity pool at 100 and admits cosmetics under pity',()=>{for(const tier of ['common','rare','epic'])expect(CAPSULE_POOL.filter(r=>r.tier===tier).reduce((n,r)=>n+r.weight,0)).toBe(100);const s=state();s.economy!.epicMisses=19;expect(draw(s,0,.9).economy!.appearances!.owned['eclipse-portal']).toBe(true);});
  it('rejects corrupted ownership and equipment on save validation',()=>{const s=state();s.economy!.appearances!.equipped['eclipse-portal']='one';expect(()=>validateGarden(s)).toThrow('外观');s.economy!.appearances!.owned['eclipse-portal']=true;s.economy!.appearances!.equipped['eclipse-portal']='unknown';expect(()=>validateGarden(s)).toThrow('外观');});
});
