import { afterEach, expect, it } from 'vitest';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { resolveFfmpegPath } from '@qbot/pipeline';
import { imageChoices, selectedImage, saveCover } from '../src/main/character-images';
import { packCharacterDir, unpackCharacter } from '../src/main/asset-pack';
let dir:string;
afterEach(async()=>{if(dir)await rm(dir,{recursive:true,force:true});});
it('selects frames from downloaded WebM, saves an isolated cover, and excludes cover metadata from packages',async()=>{
  dir=await mkdtemp(path.join(os.tmpdir(),'qbot-images-'));await mkdir(path.join(dir,'actions'));
  const ffmpeg=await resolveFfmpegPath();
  await promisify(execFile)(ffmpeg,['-v','error','-f','lavfi','-i','color=c=red:s=48x48:d=1','-c:v','libvpx-vp9',path.join(dir,'actions/st_one.webm')],{windowsHide:true});
  const manifest={id:'test',sourceImage:'source.png',turnaround:'',actions:{},customActions:{st_one:{status:'done',webm:'actions/st_one.webm'}},stickerLibrary:{items:[{id:'st_one',name:'无聊'}]}};
  await writeFile(path.join(dir,'manifest.json'),JSON.stringify(manifest));await writeFile(path.join(dir,'source.png'),'original-reference');
  const selection={kind:'action',actionId:'st_one',seconds:0.3} as const;
  const choices=await imageChoices(dir);expect(choices.some(c=>c.label==='无聊')).toBe(true);
  const png=await selectedImage(dir,selection);expect(png.subarray(1,4).toString()).toBe('PNG');
  await saveCover(dir,selection);
  expect(await readFile(path.join(dir,'source.png'),'utf8')).toBe('original-reference');
  expect(JSON.parse(await readFile(path.join(dir,'manifest.json'),'utf8'))).toEqual(manifest);
  const pack=await packCharacterDir(dir);const unpacked=path.join(dir,'unpacked');await unpackCharacter(pack.buffer,unpacked);
  expect(await readFile(path.join(unpacked,'source.png'),'utf8')).toBe('original-reference');
  await expect(readFile(path.join(unpacked,'cover.png'))).rejects.toThrow();
  await expect(readFile(path.join(unpacked,'.cover.json'))).rejects.toThrow();
  await expect(selectedImage(dir,{...selection,seconds:5})).rejects.toThrow('没有可用帧');
  await expect(selectedImage(dir,{...selection,seconds:-1})).rejects.toThrow('帧时间无效');
  await expect(selectedImage(dir,{...selection,actionId:'../outside'})).rejects.toThrow('动作不可用');
},20000);
