import {describe,it,expect} from 'vitest';
import {initialGarden,transition,validateGarden} from '../src/main/garden/rules';
import {enableV3,advanceV3,poisson,makeV3Plant,breedV3} from '../src/main/garden/v3-rules';
import {ensureLife} from '../src/main/garden/life-rules';
import {SPECIES,TRAITS,LEVEL_XP,needsReveal,traitSlot,type Trait,type Produce,type Species} from '../src/shared/garden';
import {V3_XP,V3_WEATHER,AFFINITIES,exposures,hourlyWeather,weatherWeights,scoreOf,qualityOf,stableSlots,geneSlots,speciesLevel,v3Value,weekKey} from '../src/shared/garden-v3';
import {dailyRandom} from '../src/shared/garden-life';
const now=Date.UTC(2026,8,22,8);let id=0;
const rng=(key='tests')=>({random:dailyRandom(key),id:()=>`v3-${++id}`});
function garden(){const r=rng(),s=initialGarden(now,r);ensureLife(s,now,r,'pet');enableV3(s,now);s.coins=10000;return s;}
function seed(s:ReturnType<typeof garden>,sp:Species='strawberry',genes:Trait[]=[]){const x={id:`seed-${++id}`,species:sp,genes,bred:false};s.seeds.push(x);return x;}
function planted(sp:Species='strawberry',genes:Trait[]=[]){let s=garden();s=transition(s,{type:'plant',seed:seed(s,sp,genes).id,plot:0},now,rng()).state;return s;}
describe('garden v3 numeric and asset invariants',()=>{
 it('gives one daily safety seed per account, never per actor or repeated refresh',()=>{const s=garden(),r=rng();ensureLife(s,now,r,'pet');const count=s.seeds.length;for(const actor of ['pet','two','three','four','five'])ensureLife(s,now,r,actor);expect(s.seeds).toHaveLength(count);ensureLife(s,now+86400000,r,'two');expect(s.seeds).toHaveLength(count+1);ensureLife(s,now,r,'pet');expect(s.seeds).toHaveLength(count+1);});
 it('never turns discovering a rare fruit into mandatory expensive daily food',()=>{const s=garden(),r=rng();s.discovered=Object.keys(SPECIES).map(sp=>sp+':base');for(let day=1;day<=30;day++){ensureLife(s,now+day*86400000,r,'pet');expect(s.life!.characters.pet.wishes.slice(0,2).every(w=>['strawberry','tomato'].includes(w.species)&&w.traits.length===0)).toBe(true);}});
 it('rejects a damaged appraisal board and missing batch before loading assets',()=>{const s=planted();delete s.plots[0]!.batch;expect(()=>validateGarden(s)).toThrow('批次');const other=garden();other.v3!.appraisals.fake={row:0,factor:1,done:false,baseKg:1,maxRows:3,history:[],board:Array(7).fill([99,99,99])};expect(()=>validateGarden(other)).toThrow('鉴定记录');});
 it('migrates old levels once while preserving old crops, fertilizer promises and oversized collections',()=>{
  const r=rng(),s=initialGarden(now,r);s.xp.lotus=LEVEL_XP[5]+10;const old=transition(s,{type:'plant',plot:0,seed:s.seeds[0].id},now,r).state;s.plots=old.plots;const before=structuredClone(s.plots[0]);enableV3(s,now);expect(speciesLevel(s.xp.lotus)).toBe(6);expect(s.plots[0]).toMatchObject(before!);expect(s.plots[0]?.legacyLevel).toBe(6);const xp=s.xp.lotus;expect(enableV3(s,now)).toBe(false);expect(s.xp.lotus).toBe(xp);expect(validateGarden(s)).toBe(s);
 });
 it('scores ordinary factors once, derives size without double counting and separates factor from fruit rarity',()=>{
  const p:Produce={id:'x',species:'pineapple',kg:1.2,traits:['honey','golden','moon','stardust','plump'],value:0,bred:false,growthVersion:3};expect(scoreOf(p)).toBe(132);expect(qualityOf(p)).toBe('gold');expect(needsReveal(p)).toBe(false);p.kg=2.4;expect(qualityOf(p)).toBe('rainbow');expect(needsReveal(p)).toBe(true);p.traits=[];expect(qualityOf(p)).toBe('blue');
 });
 it('preserves the second accessory index after removing the first',()=>{expect(stableSlots(['moon'],[null,null,'shiny','moon'])).toEqual([null,null,null,'moon']);expect(stableSlots(['moon','petals'],[null,null,null,'moon'])).toEqual([null,null,'petals','moon']);});
 it('provides all nine affinity pools, eleven weather pools, finite normalized weights and an SSR at least each thirteen hours',()=>{
  expect(Object.keys(AFFINITIES)).toHaveLength(9);expect(Object.keys(V3_WEATHER)).toHaveLength(11);
  for(const pool of Object.values(AFFINITIES))for(const t of pool)expect(TRAITS[t]).toBeDefined();
  for(let h=450000;h<450200;h++){expect(Array.from({length:13},(_,i)=>V3_WEATHER[hourlyWeather(h+i,'room-a')].grade).includes('SSR')).toBe(true);expect(hourlyWeather(h,'room-a')).toBe(hourlyWeather(h,'room-a'));}
  for(const w of Object.keys(V3_WEATHER) as (keyof typeof V3_WEATHER)[])expect(weatherWeights(w).reduce((a,b)=>a+b,0)).toBeGreaterThan(0);
 });
 it('clips weather durations and keeps the sowing realm when changing rooms',()=>{const s=planted();s.v3!.realm='new-room';const b=s.plots[0]!.batch!;const history=exposures(now,b.seedlingEnd,b.realm);expect(history.reduce((a,b)=>a+b.ms,0)).toBe(b.seedlingEnd-now);advanceV3(s,b.seedlingEnd);expect(b.exposure).toEqual(history);});
 it('settles exactly once, including across save/reload and long mature display',()=>{const s=planted();const end=s.plots[0]!.batch!.seedlingEnd;expect(advanceV3(s,end-1)).toBe(false);expect(advanceV3(s,end)).toBe(true);const p=structuredClone(s.plots[0]);const restored=validateGarden(JSON.parse(JSON.stringify(s)));advanceV3(restored,end+90*86400000);expect(restored.plots[0]).toEqual(p);});
 it('holds conflicting candidates without silent replacement, and prevents trading until chosen',()=>{let s=planted('pineapple',['honey','golden','moon','stardust']);advanceV3(s,now+86400000);const p=s.plots[0]!;p.batch!.candidates=['daylight'];p.revealed=true;expect(()=>transition(s,{type:'harvest',plot:0},now+86400000,rng())).toThrow('待选择');s=transition(s,{type:'resolveFactors',target:p.id,chosen:['honey','golden','moon','stardust']},now+86400000,rng()).state;expect(s.plots[0]!.batch!.candidates).toEqual([]);expect(()=>transition(s,{type:'resolveFactors',target:p.id,chosen:[]},now+86400000,rng())).toThrow('没有待选');});
 it('32 qualified SSR misses guarantee a retained candidate even at full capacity, with no repeated event credit',()=>{let s=planted('pineapple',['honey','golden','moon','stardust']);const p=s.plots[0]!,h=450007-(450007%13)+12;p.plantedAt=h*3600000;p.batch!.seedlingEnd=p.plantedAt+1000;p.batch!.naturalReadyAt=p.readyAt=p.plantedAt+2000;s.v3!.rainbowMisses=32;advanceV3(s,p.batch!.seedlingEnd);expect([...p.traits,...p.batch!.candidates].some(t=>TRAITS[t].tier==='rainbow')).toBe(true);const misses=s.v3!.rainbowMisses;advanceV3(s,p.readyAt+1);expect(s.v3!.rainbowMisses).toBe(misses);expect(new Set(s.v3!.pityEvents).size).toBe(s.v3!.pityEvents.length);});
 it('allows one fertilizer per cycle, rejects late fertilizer without consuming it, and resets on regrowth',()=>{let s=planted();s=transition(s,{type:'fertilize',plot:0,fertilizer:'speed'},now,rng()).state;expect(s.plots[0]!.readyAt-now).toBe(30*60000*.8);expect(()=>transition(s,{type:'fertilize',plot:0,fertilizer:'weight'},now,rng())).toThrow();const end=s.plots[0]!.readyAt;advanceV3(s,end);s.plots[0]!.batch!.candidates=[];s.plots[0]!.revealed=true;s=transition(s,{type:'harvest',plot:0},end,rng()).state;expect(s.plots[0]!.fertilizers).toEqual([]);const before=s.fertilizers.weight;expect(()=>transition(s,{type:'fertilize',plot:0,fertilizer:'weight'},s.plots[0]!.batch!.seedlingEnd,rng())).toThrow('幼苗期');expect(s.fertilizers.weight).toBe(before);});
 it('samples Poisson mean instead of treating lambda 5 as a hard count cap',()=>{const random=dailyRandom('poisson');const values=Array.from({length:50000},()=>poisson(5,random));expect(values.reduce((a,b)=>a+b,0)/values.length).toBeCloseTo(5,1);expect(Math.max(...values)).toBeGreaterThan(5);});
 it('uses ten growth levels and a Monday 04:00 weekly boundary',()=>{expect(V3_XP).toHaveLength(10);expect(speciesLevel(1000)).toBe(10);const monday=Date.UTC(2026,8,20,20);expect(weekKey(monday)-weekKey(monday-1)).toBe(1);});
 it('caps short crop sale premium and makes long crops pay for their growing time',()=>{for(const sp of Object.keys(SPECIES) as Species[]){const p={species:sp,kg:SPECIES[sp].kg*8,traits:['galaxycore','daylight','stardust','halo'] as Trait[],yieldCount:SPECIES[sp].harvests};expect(v3Value(p)).toBeLessThanOrEqual(Math.ceil(SPECIES[sp].price/SPECIES[sp].harvests+24*SPECIES[sp].minutes/60*2.5*3));}});
 it('separates gene and mass pity, consumes oil once and keeps both parents',()=>{const s=garden(),a=makeV3Plant(s,seed(s,'apple',['golden','moon']),0,now,rng()),b:Produce={id:'father',species:'apple',kg:2,traits:['golden','moon','giant'],slots:geneSlots(['golden','moon']),value:500,bred:false,growthVersion:3,revealed:true};s.v3!.geneMisses=s.v3!.sizeMisses=9;const child=breedV3(s,a,b,{type:'breed',first:a.id,second:b.id},now,{random:()=>.99,id:()=> 'child'});expect(child.genes).toHaveLength(1);expect(child.massGene).toBe('giant');expect(child.lineage?.parents).toHaveLength(2);expect(s.v3!.geneMisses).toBe(0);expect(s.v3!.sizeMisses).toBe(0);expect(s.v3!.oils.normal).toBe(1);expect(a.bred&&b.bred).toBe(true);});
 it('does not consume weight pity when there is no valid weight candidate and rejects mini fathers',()=>{const s=garden(),a=makeV3Plant(s,seed(s,'apple'),0,now,rng()),b:Produce={...a,id:'dad',traits:[]};s.v3!.sizeMisses=8;breedV3(s,a,b,{type:'breed',first:a.id,second:b.id},now,rng());expect(s.v3!.sizeMisses).toBe(8);b.traits=['mini'];expect(()=>breedV3(s,a,b,{type:'breed',first:a.id,second:b.id},now,rng())).toThrow('迷你');});
 it('persists an appraisal board, locks pending fruit and never destroys it on a loss',()=>{let s=garden();s.xp.apple=V3_XP[4];const p:Produce={id:'appraise',species:'apple',kg:.8,traits:['golden'],slots:geneSlots(['golden']),value:400,bred:false,growthVersion:3,revealed:true};s.produce=[p];s=transition(s,{type:'appraiseStart',target:p.id},now,rng()).state;const a=s.v3!.appraisals[p.id];expect(a.board).toHaveLength(7);expect(()=>transition(s,{type:'sell',id:p.id},now,rng())).toThrow('鉴定');s=validateGarden(JSON.parse(JSON.stringify(s)));s=transition(s,{type:'appraisePick',target:p.id,column:a.board[0].indexOf(.9)},now,rng()).state;expect(s.produce).toHaveLength(1);expect(s.produce[0].kg).toBe(.72);expect(s.v3!.appraisals[p.id].done).toBe(true);expect(()=>transition(s,{type:'appraiseStart',target:p.id},now,rng())).toThrow('每果一次');});
 it('protects locked keeps from selling, feeding and breeding',()=>{const s=garden();s.produce=[{id:'kept',species:'strawberry',kg:1,traits:['golden'],value:100,bred:false,locked:true,growthVersion:3}];expect(()=>transition(s,{type:'sell',id:'kept'},now,rng())).toThrow('收藏');expect(()=>transition(s,{type:'feed',wish:s.life!.characters.pet.wishes[0].id,produce:'kept'},now,rng(),{actor:'pet'})).toThrow('收藏');});
});
